title: Finn's Site
author: Finnegan
email: finnismean@imadog.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Finnegan and I am not a very nice dog

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
